version: '2'
services:
  nginx:
    image: nginx:1.10
    volumes:
      - ./test/conf:/etc/nginx/conf.d
    ports:
      - 0.0.0.0:80:80
    depends_on:
      - auth
      - data

  auth:
    build: ./auth_service
    volumes:
      - ./auth_service:/code
    depends_on:
      - mongodb

  data:
    build: ./data_service
    volumes:
      - ./data_service:/code
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.2
    volumes:
      - ./test/data:/test/data
